### ISSUE TITLE
Quickstart guide?

### ISSUE THREAD

**Issue by connecteev** [openai/gpt-2-output-dataset#10]
I'd love to start using OpenAI's datasets and packages..in particular this one for text generation. Sorry for the 'basic' question but is there a beginner's tutorial for getting started somewhere? Perhaps a detailed installation guide?

**Comment by jongwook** [comment]
I suggest starting with [the Huggingface Transformer](https://huggingface.co/transformers/examples.html#language-generation) interface which has very clean API and much more beginner friendly.
