### ISSUE TITLE
Issues running the detection training code

### ISSUE THREAD

**Issue by dadelani** [openai/gpt-2-output-dataset#11]
Thank you for releasing the code for training the detector. I want to fine-tune the detector on the amazon reviews you released but I have some issues.

The file "train.py" in "detector" directory requires some python functions in some directories (dataset, download, utils) that are missing. Can you please help? 

The following imports gives error:

from .dataset import Corpus, EncodedDataset
from .download import download
from .utils import summary, distributed

Thank you

**Comment by jongwook** [comment]
You'll need to launch the script as a module, from the upper directory:

```
python -m detector.train
```

Check out [README.md](https://github.com/openai/gpt-2-output-dataset/blob/master/detector/README.md) for more details.

**Comment by dadelani** [comment]
I see, thank you very much for your reply.
