### ISSUE TITLE
Access denied to model checkpoints

### ISSUE THREAD

**Issue by artidoro** [openai/gpt-2-output-dataset#27]
Hello, when trying to get the two model checkpoints as indicated [here](https://github.com/openai/gpt-2-output-dataset/tree/master/detector#downloading-a-pre-trained-detector-model) using:
```
wget https://storage.googleapis.com/gpt-2/detector-models/v1/detector-large.pt
```
I get the error: `ERROR 403: Forbidden.`

It seems like permissions are not allowing me to download the files. Could you help me get access to the models?

**Comment by jongwook** [comment]
Hi! Thanks for catching this - it should be https://openaipublic.azureedge.net/gpt-2/detector-models/v1/detector-large.pt now. We'll update the code and doc shortly.

**Comment by jongwook** [comment]
Updated in 2c102400c7e4e698acd3f0e51d3b6cf1c637c0fe
