### ISSUE TITLE
download_model.py [117M | 345M | 355M | 762M | 774M | 1542M] -> The specified bucket does not exist

### ISSUE THREAD

**Issue by gmohsyan** [openai/gpt-2-output-dataset#29]
Hi,

I am just starting with gtp-2 and wanted to run some tutorials.
For example, running `python3 download_models.py 117M` outputs

```
python3 download_model.py 117M
Fetching checkpoint: 1.00kit [00:00, 320kit/s]
Fetching encoder.json: 1.00kit [00:00, 428kit/s]
Fetching hparams.json: 1.00kit [00:00, 302kit/s]
Fetching model.ckpt.data-00000-of-00001: 1.00kit [00:00, 333kit/s]
Fetching model.ckpt.index: 1.00kit [00:00, 366kit/s]
Fetching model.ckpt.meta: 1.00kit [00:00, 348kit/s]
Fetching vocab.bpe: 1.00kit [00:00, 427kit/s]
```

inspecting any of those files gives:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

I also don't see any data when I try:
https://console.cloud.google.com/storage/browser/gpt-2/output-dataset/v1

anything I am doing wrong?
best,
gmohsyan

**Comment by jongwook** [comment]
It looks like you're referring to the [`download_model.py`](https://github.com/openai/gpt-2/blob/master/download_model.py) file in the GPT-2 repository. We [updated](https://github.com/openai/gpt-2/commit/a74da5d99abaaba920de8131d64da2862a8f213b) the URLs recently, so try pulling from the repo again.

**Comment by gmohsyan** [comment]
Thanks a lot! 
I indeed had the old version - didn't realize the change.
