### ISSUE TITLE
Temperature for detectability baselines

### ISSUE THREAD

**Issue by woctezuma** [openai/gpt-2-output-dataset#3]
The temperature is different for each model for detectability baselines.

| Model | Temperature 1 | Top-K 40 |
| ----- | ------ | ------ |
| 117M  | 88.29% | 96.79% |
| 345M  | 88.94% | 95.22% |
| 762M  | 77.16% | 94.43% |
| 1542M | 74.31% | 92.69% |

It seems that the temperature is chosen closer to:
- 0.9 for the `117M `and `345M `models, 
- 0.75 for the `762M` and `1542M` models.

Did you optimize the temperature for each model?
If so, is that a recommended setting when we use your models for other applications?

I mention so because a Python package based on GPT-2 uses [0.7 as the default temperature](https://github.com/minimaxir/gpt-2-simple/issues/43), with your `117M `and `345M `models, and that might not be an optimal default value.

**Comment by WuTheFWasThat** [comment]
those numbers are accuracies, not temperatures

**Comment by woctezuma** [comment]
Oops. Sorry. I see it now: `temperature 1`.
